
title: Olivia's project page
description: > # this means to ignore newlines until "baseurl:"
  Data Science project and blog page.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://porphyrin.github.io"

# Author Settings
author: Olivia Warren
author-img: ow_headshot.jpg
about-author: data scientist. python enthusiast. loves houseplants, but struggles to keep them alive.
github: porphyrin
linkedin: olivia-warren

# Tracker
# analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 3
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
